# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q5Bi1hnfy3Nysm9g8qAHA7RmMazTQ-LV
"""

from PIL import Image
import cv2
import numpy as np
import pandas as pd

from google.colab import files
uploaded = files.upload()

image = Image.open("Screenshot 2025-04-12 223410.png")
image_cv = cv2.cvtColor(np.array(image), cv2.COLOR_RGB2BGR)

gray = cv2.cvtColor(image_cv, cv2.COLOR_BGR2GRAY)
thresh = cv2.threshold(gray, 150, 255, cv2.THRESH_BINARY_INV)[1]

pip install paddleocr paddlepaddle

from paddleocr import PaddleOCR

ocr = PaddleOCR(use_angle_cls=True, lang='en')
results = ocr.ocr("Screenshot 2025-04-12 223410.png", cls=True)

text = "\n".join([line[1][0] for line in results[0]])
print("📄 PaddleOCR Output:\n", text)

text

course_df = pd.read_csv("Coursera.csv")

known_courses = course_df["course"].dropna().str.lower().tolist()

course_df

def verify_certificate(text, user_name, known_courses):
    matched_courses = [c for c in known_courses if c in text.lower()]
    platform_found = any(p in text.lower() for p in ["coursera", "udemy", "edx", "skillshare"])
    user_verified = user_name in text

    return {
        "courses_found": matched_courses,
        "platform_verified": platform_found,
        "user_name_verified": user_verified,
        "valid_certificate": bool(matched_courses and platform_found)
    }

result = verify_certificate(text, user_name="Manil Modi", known_courses=known_courses)
print(result)

