# -*- coding: utf-8 -*-
"""Job market analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17t_CQZRuzHneltWXvD0ZXOCq_zl1J82m
"""

import pandas as pd
import numpy as np

from google.colab import files
uploaded = files.upload()

df=pd.read_csv("ai_job_market_insights.csv")

df

import plotly.express as px
import plotly.graph_objects as go

fig = px.bar(
    df.groupby("Job_Title", as_index=False)["Salary_USD"].mean().sort_values(by="Salary_USD", ascending=False),
    x="Job_Title",
    y="Salary_USD",
    title="Average Salary by Job Title",
    text_auto=True
)
fig.update_traces(textposition="outside")
fig.update_layout(xaxis_tickangle=-45, showlegend=False)
fig.show()

fig = px.pie(
    df,
    names="Industry",
    title="Distribution of Jobs by Industry",
    hole=0.3
)
fig.update_traces(textinfo='percent+label')
fig.show()

fig = px.histogram(
    df,
    x="Salary_USD",
    nbins=30,
    title="Salary Distribution",
    marginal="box"
)
fig.update_traces(marker_color="indianred")
fig.show()

fig = px.box(
    df,
    x="AI_Adoption_Level",
    y="Salary_USD",
    title="Salary vs AI Adoption Level by Company"
)
fig.show()

fig = px.histogram(
    df,
    x="Industry",
    color="Remote_Friendly",
    title="Remote-Friendly Jobs by Industry",
    barmode="group",
    text_auto=True
)
fig.update_layout(xaxis_tickangle=-45)
fig.show()

fig = px.histogram(
    df,
    x="Industry",
    color="Automation_Risk",
    title="Automation Risk factor for jobs",
    barmode="group",
    text_auto=True
)
fig.update_layout(xaxis_tickangle=-45)
fig.show()

fig = px.histogram(
    df,
    x="Industry",
    color="AI_Adoption_Level",
    title="Automation Adoption factor for jobs",
    barmode="group",
    text_auto=True
)
fig.update_layout(xaxis_tickangle=-45)
fig.show()

fig = px.histogram(
    df,
    x="Job_Title",
    color="Job_Growth_Projection",
    title="Job Growth Projections",
    barmode="group",
    text_auto=True,
    color_discrete_map={
        "High": "#1f77b4",
        "Moderate": "#ff7f0e",
        "Low": "#2ca02c"
    }
)
fig.update_layout(xaxis_tickangle=-45)
fig.show()

