# -*- coding: utf-8 -*-
"""Job Recommendation

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xSJfmM-jFGzYlbbazTMs_t4nwuQf9sp6
"""

import pandas as pd

from google.colab import files
uploaded = files.upload()

df=pd.read_csv("ai_job_market_insights.csv")

df

df.info()

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans
from sklearn.metrics.pairwise import cosine_similarity

# Vectorize the job skills
vectorizer = TfidfVectorizer(stop_words='english')
X = vectorizer.fit_transform(df['Required_Skills'])

# Apply KMeans clustering
kmeans = KMeans(n_clusters=5, random_state=42)
clusters = kmeans.fit_predict(X)
df['Cluster'] = clusters

# Example user resume skills as a list
user_skills_list = ['AWS',
 'Computer Networking',
 'EC2',
 'Kubernetes',
 'azure',
 'c',
 'cnn',
 'communication',
 'data structures',
 'git',
 'ml',
 'sql',
 'supervised learning',
 'teamwork']

# Convert list to a comma-separated string for vectorizer
user_skills_text = ', '.join(user_skills_list)

# Transform user input using same vectorizer
user_vec = vectorizer.transform([user_skills_text])

# Compute similarity with all job vectors
similarities = cosine_similarity(user_vec, X).flatten()

# Recommend top 5 jobs
top_indices = similarities.argsort()[-5:][::-1]
recommended_jobs = df.iloc[top_indices]

print("🎯 Top 5 Recommended Jobs for You:\n")
print(recommended_jobs)









